# Generated by Django 5.2.7 on 2025-11-22 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(help_text='Appointment date')),
                ('scheduled_time', models.TimeField(help_text='Appointment time')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', help_text='Appointment status', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or requirements')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(help_text='Agent managing the appointment', on_delete=django.db.models.deletion.CASCADE, related_name='agent_appointments', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(help_text='Client requesting the viewing', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(help_text='Property to view', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='listings.listing')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ['scheduled_date', 'scheduled_time'],
                'indexes': [models.Index(fields=['scheduled_date', 'scheduled_time'], name='appointment_schedul_59e8bc_idx'), models.Index(fields=['status'], name='appointment_status_8fe9d7_idx')],
                'unique_together': {('listing', 'scheduled_date', 'scheduled_time')},
            },
        ),
    ]
