# Generated by Django 5.2.7 on 2025-10-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=10)),
                ('building_name', models.CharField(max_length=10)),
                ('house_size', models.CharField(max_length=80)),
                ('house_rent', models.IntegerField(default=0)),
                ('contact_info', models.CharField(max_length=40)),
                ('amenities', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('availability', models.CharField(choices=[('ready_for_occupancy', 'Ready To Occupy'), ('pending', 'Pending'), ('occupied', 'Occupied')], max_length=100)),
            ],
        ),
    ]
