# Generated by Django 5.2.7 on 2025-11-17 05:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Property title', max_length=200)),
                ('description', models.TextField(help_text='Detailed property description')),
                ('property_type', models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('condo', 'Condo'), ('townhouse', 'Townhouse'), ('land', 'Land')], help_text='Type of property', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('sold', 'Sold'), ('inactive', 'Inactive')], default='active', help_text='Current listing status', max_length=20)),
                ('address', models.CharField(help_text='Street address', max_length=255)),
                ('city', models.CharField(help_text='City', max_length=100)),
                ('state', models.CharField(help_text='State/Province', max_length=100)),
                ('zip_code', models.CharField(help_text='Postal/ZIP code', max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate', max_digits=9, null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Property price', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('bedrooms', models.IntegerField(help_text='Number of bedrooms', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('bathrooms', models.DecimalField(decimal_places=1, help_text='Number of bathrooms', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('square_feet', models.IntegerField(help_text='Property size in square feet', validators=[django.core.validators.MinValueValidator(0)])),
                ('lot_size', models.IntegerField(blank=True, help_text='Lot size in square feet', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('year_built', models.IntegerField(blank=True, help_text='Year the property was built', null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2100)])),
                ('parking_spaces', models.IntegerField(default=0, help_text='Number of parking spaces', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('has_garage', models.BooleanField(default=False, help_text='Has garage')),
                ('has_pool', models.BooleanField(default=False, help_text='Has swimming pool')),
                ('has_garden', models.BooleanField(default=False, help_text='Has garden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('agent', models.ForeignKey(help_text='Agent managing this listing', on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Listing',
                'verbose_name_plural': 'Listings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Property image', upload_to='listings/%Y/%m/')),
                ('caption', models.CharField(blank=True, help_text='Image caption or description', max_length=200)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary/featured image')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(help_text='Associated listing', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.listing')),
            ],
            options={
                'verbose_name': 'Listing Image',
                'verbose_name_plural': 'Listing Images',
                'ordering': ['order', '-is_primary', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status', 'is_deleted'], name='listings_li_status_da7616_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['city', 'property_type'], name='listings_li_city_a4f39b_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['price'], name='listings_li_price_d6caaa_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['-created_at'], name='listings_li_created_92fa22_idx'),
        ),
    ]
