# Generated by Django 5.2.7 on 2026-02-14 06:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_savedlisting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='savedlisting',
            name='listings_savedlisting_unique_user_listing',
        ),
        migrations.RenameIndex(
            model_name='savedlisting',
            new_name='listings_sa_user_id_40c7df_idx',
            old_name='listings_sav_user_id_7e0f0d_idx',
        ),
        migrations.AlterUniqueTogether(
            name='savedlisting',
            unique_together={('user', 'listing')},
        ),
    ]
