# Generated by Django 5.2.7 on 2026-01-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='target_user_type',
            field=models.CharField(choices=[('agent', 'Agent/Realtor'), ('client', 'Client/User')], default='agent', help_text='Target user type: Agent for realtors posting listings, Client for users viewing listings', max_length=10),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_listings',
            field=models.IntegerField(blank=True, help_text='Maximum listings allowed (null = unlimited). Only applicable for agent plans.', null=True),
        ),
    ]
