# Generated by Django 5.2.7 on 2026-02-15 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0003_remove_savedlisting_listings_savedlisting_unique_user_listing_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(help_text='Message content')),
                ('read_at', models.DateTimeField(blank=True, help_text='When the recipient read the message', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(blank=True, help_text='Optional: listing this message is about', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='listings.listing')),
                ('recipient', models.ForeignKey(help_text='User who receives the message', on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(help_text='User who sent the message', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['sender', 'recipient'], name='messaging_m_sender__f68e92_idx'), models.Index(fields=['recipient', 'read_at'], name='messaging_m_recipie_e8b3f3_idx')],
            },
        ),
    ]
